name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1️⃣ Install pnpm before Node caching
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9  # match your local pnpm version

      # 2️⃣ Then set up Node + pnpm cache
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # 3️⃣ Install deps
      - name: Install dependencies
        run: pnpm install

      # 4️⃣ Panda CSS codegen (optional)
      - name: Panda codegen
        run: pnpm panda watch

      # 5️⃣ Build the app
      - name: Build
        run: pnpm build
        env:
          BASE_PATH: /

      # 6️⃣ Copy index.html → 404.html for GitHub Pages routing
      - name: Copy 404.html
        run: cp dist/index.html dist/404.html

      # 7️⃣ Deploy to GitHub Pages
      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
