name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install pnpm before Node caching
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      # Then set up Node + pnpm cache
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # Install deps
      - name: Install dependencies
        run: pnpm install

      # Panda CSS codegen
      - name: Panda codegen
        run: pnpm panda watch

      # Build the app
      - name: Build
        run: pnpm build
        env:
          BASE_PATH: /

      # Copy index.html → 404.html for GitHub Pages routing
      - name: Copy 404.html
        run: cp dist/index.html dist/404.html

      # Deploy to GitHub Pages
      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
